# Generated by Django 4.2.4 on 2023-09-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0003_alter_aposta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='método',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
