# Generated by Django 4.2.4 on 2023-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0004_aposta_método'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='método',
            field=models.CharField(max_length=50),
        ),
    ]
