# Generated by Django 4.2.4 on 2023-08-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=60, verbose_name='Time 1')),
                ('team2', models.CharField(max_length=60, verbose_name='Time 2')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do evento')),
            ],
        ),
    ]
