# Generated by Django 4.2.4 on 2023-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Em jogo', 'Em jogo'), ('Fechado', 'Fechado')], max_length=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='date',
            field=models.DateTimeField(verbose_name='Data do evento'),
        ),
    ]
