# Generated by Django 4.2.4 on 2023-08-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='maney',
            new_name='money',
        ),
    ]
