# Generated by Django 4.2.4 on 2023-08-31 08:20

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_user_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_money',
            name='money',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='BRL', max_digits=10),
        ),
    ]
