# Generated by Django 4.2.4 on 2023-09-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_aposta_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='resultado',
            new_name='escolha',
        ),
    ]
