# Generated by Django 4.2.4 on 2023-09-02 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_aposta_valor_aposta_valor_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_money',
            new_name='dados',
        ),
    ]
