# Generated by Django 4.2.4 on 2023-09-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_dados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aposta',
        ),
    ]
